-- MySQL Script generated by MySQL Workbench
-- Thu Oct 11 10:32:09 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema PHP2_ExoFinal
-- -----------------------------------------------------
-- Modèle correspondant à l'exercice final du module de formation php2-avancé de Cefii
DROP SCHEMA IF EXISTS `PHP2_ExoFinal` ;

-- -----------------------------------------------------
-- Schema PHP2_ExoFinal
--
-- Modèle correspondant à l'exercice final du module de formation php2-avancé de Cefii
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `PHP2_ExoFinal` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `PHP2_ExoFinal` ;

-- -----------------------------------------------------
-- Table `PHP2_ExoFinal`.`produits`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PHP2_ExoFinal`.`produits` ;

CREATE TABLE IF NOT EXISTS `PHP2_ExoFinal`.`produits` (
  `idproduits` INT NOT NULL AUTO_INCREMENT,
  `reference` VARCHAR(20) NOT NULL,
  `nom` VARCHAR(45) NULL,
  `quantite` INT NULL DEFAULT 0,
  `pdt_commentaire` VARCHAR(45) NULL,
  PRIMARY KEY (`idproduits`),
  UNIQUE INDEX `reference_UNIQUE` (`reference` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PHP2_ExoFinal`.`fournisseurs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PHP2_ExoFinal`.`fournisseurs` ;

CREATE TABLE IF NOT EXISTS `PHP2_ExoFinal`.`fournisseurs` (
  `idfournisseurs` INT NOT NULL AUTO_INCREMENT,
  `societe` VARCHAR(45) NOT NULL,
  `adresse` VARCHAR(45) NULL,
  `cp` VARCHAR(5) NULL,
  `ville` VARCHAR(45) NULL,
  `commentaire` VARCHAR(45) NULL,
  PRIMARY KEY (`idfournisseurs`),
  UNIQUE INDEX `societe_UNIQUE` (`societe` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PHP2_ExoFinal`.`produit_fournisseurs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PHP2_ExoFinal`.`produit_fournisseurs` ;

CREATE TABLE IF NOT EXISTS `PHP2_ExoFinal`.`produit_fournisseurs` (
  `fk_idproduits` INT NOT NULL,
  `fk_idfournisseurs` INT NOT NULL,
  PRIMARY KEY (`fk_idproduits`, `fk_idfournisseurs`),
  INDEX `fk_pdt_frns_frn_idx` (`fk_idfournisseurs` ASC) VISIBLE,
  INDEX `fk_pdt_frns_pdt_idx` (`fk_idproduits` ASC) VISIBLE,
  CONSTRAINT `fk_produit_fournisseurs_idproduits`
    FOREIGN KEY (`fk_idproduits`)
    REFERENCES `PHP2_ExoFinal`.`produits` (`idproduits`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produit_fournisseurs_idfournisseurs`
    FOREIGN KEY (`fk_idfournisseurs`)
    REFERENCES `PHP2_ExoFinal`.`fournisseurs` (`idfournisseurs`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
